channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=23.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - pandas==1.5.3
  - psutil==5.9.4
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - xgboost==1.7.5
name: mlflow-env
